name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/blue-robot-mascot-logo-icon-design675467-55-1-traced.png
    - assets/page-1/images/vuesax-linear-export.png
    - assets/page-1/images/pillatesexercisefitnesspilatesstrengthicon-1.png
    - assets/page-1/images/vuesax-bold-send.png
    - assets/page-1/images/frame-33-bg.png
    - assets/page-1/images/vuesax-linear-arrow-right.png
    - assets/page-1/images/vuesax-linear-volume-high.png
    - assets/page-1/images/vuesax-linear-arrow-right-6eU.png
    - assets/page-1/images/vuesax-linear-volume-high-cPA.png
    - assets/page-1/images/vuesax-linear-arrow-left.png
    - assets/page-1/images/vuesax-linear-arrow-right-LnC.png
    - assets/page-1/images/vuesax-linear-microphone-2.png
    - assets/page-1/images/vuesax-linear-edit-2.png
    - assets/page-1/images/vuesax-linear-arrow-right-is2.png
    - assets/page-1/images/vuesax-bold-send-JKz.png
    - assets/page-1/images/blue-robot-mascot-logo-icon-design675467-55-1-traced-3tC.png
    - assets/page-1/images/vuesax-linear-volume-high-N6t.png
    - assets/page-1/images/vuesax-bold-send-yrG.png
    - assets/page-1/images/blue-robot-mascot-logo-icon-design675467-55-1-traced-1.png
    - assets/page-1/images/blue-robot-mascot-logo-icon-design675467-55-1-traced-1-qHS.png
    - assets/page-1/images/blue-robot-mascot-logo-icon-design675467-55-1-traced-1-8sS.png
    - assets/page-1/images/blue-robot-mascot-logo-icon-design675467-55-1-traced-1-fTv.png
    - assets/page-1/images/vuesax-linear-export-XuJ.png
    - assets/page-1/images/vuesax-linear-microphone-2-V6g.png
    - assets/page-1/images/vuesax-linear-export-pUY.png
    - assets/page-1/images/botanicalnatureplantleafgardenicon-1.png
    - assets/page-1/images/blue-robot-mascot-logo-icon-design675467-55-1-traced-1-s3e.png
    - assets/page-1/images/vuesax-bold-send-mLc.png
    - assets/page-1/images/blue-robot-mascot-logo-icon-design675467-55-1-traced-1-j68.png
    - assets/page-1/images/blue-robot-mascot-logo-icon-design675467-55-1-traced-1-xQg.png
    - assets/page-1/images/image-10.png
    - assets/page-1/images/frame-40.png
    - assets/page-1/images/vuesax-linear-microphone-2-VDz.png
    - assets/page-1/images/frame-40-dsE.png
    - assets/page-1/images/vuesax-linear-arrow-right-2zU.png
    - assets/page-1/images/vuesax-linear-export-mLt.png
    - assets/page-1/images/frame-33.png
    - assets/page-1/images/vuesax-linear-volume-high-X6G.png
    - assets/page-1/images/vuesax-linear-arrow-right-9qi.png
    - assets/page-1/images/vuesax-linear-arrow-right-SXJ.png
    - assets/page-1/images/vuesax-linear-arrow-left-nWc.png
    - assets/page-1/images/vuesax-bold-send-Qfi.png
    - assets/page-1/images/blue-robot-mascot-logo-icon-design675467-55-1-traced-1-oSx.png
    - assets/page-1/images/vuesax-linear-export-zZN.png
    - assets/page-1/images/blue-robot-mascot-logo-icon-design675467-55-1-traced-1-qK6.png
    - assets/page-1/images/frame-40-GYp.png
    - assets/page-1/images/blue-robot-mascot-logo-icon-design675467-55-1-traced-1-yVA.png
    - assets/page-1/images/vuesax-linear-volume-high-eDv.png
    - assets/page-1/images/vuesax-linear-microphone-2-xNL.png
    - assets/page-1/images/image-10-ajS.png
    - assets/page-1/images/vuesax-linear-arrow-left-ZwN.png
    - assets/page-1/images/frame-40-VPe.png
    - assets/page-1/images/image-10-bwE.png
    - assets/page-1/images/image-10-rDN.png
    - assets/page-1/images/vuesax-linear-arrow-left-pkQ.png
    - assets/page-1/images/image-10-UYQ.png
    - assets/page-1/images/image-11.png
    - assets/page-1/images/frame-40-7RS.png
    - assets/page-1/images/frame-40-Soa.png
    - assets/page-1/images/image-10-CFa.png
    - assets/page-1/images/frame-63.png
    - assets/page-1/images/blue-robot-mascot-logo-icon-design675467-55-1-traced-1-15r.png
    - assets/page-1/images/frame-40-16G.png
    - assets/page-1/images/image-15.png
    - assets/page-1/images/image-10-7gL.png
    - assets/page-1/images/image-11-tVN.png
    - assets/page-1/images/vuesax-linear-textalign-justifyright.png
    - assets/page-1/images/image-14.png
    - assets/page-1/images/blue-robot-mascot-logo-icon-design675467-55-1-traced-1-jWY.png
    - assets/page-1/images/blue-robot-mascot-logo-icon-design675467-55-1-traced-1-Eqv.png
    - assets/page-1/images/vuesax-linear-translate.png
    - assets/page-1/images/frame-41.png
    - assets/page-1/images/image-10-6Zv.png
    - assets/page-1/images/blue-robot-mascot-logo-icon-design675467-55-1-traced-1-kTr.png
    - assets/page-1/images/vuesax-linear-arrow-left-bfN.png
    - assets/page-1/images/frame-40-7di.png
    - assets/page-1/images/image-11-92G.png
    - assets/page-1/images/image-11-x2t.png
    - assets/page-1/images/frame-66.png
    - assets/page-1/images/image-11-2M6.png
    - assets/page-1/images/vuesax-linear-arrow-right-9S8.png
    - assets/page-1/images/vuesax-linear-microphone-2-5qa.png
    - assets/page-1/images/image-11-9tc.png
    - assets/page-1/images/image-12.png
    - assets/page-1/images/vuesax-linear-arrow-left-mkt.png
    - assets/page-1/images/image-11-DYC.png
    - assets/page-1/images/image-11-C5n.png
    - assets/page-1/images/image-10-fzx.png
    - assets/page-1/images/blue-robot-mascot-logo-icon-design675467-55-1-traced-1-CYQ.png
    - assets/page-1/images/image-2.png
    - assets/page-1/images/image-5.png
    - assets/page-1/images/image-11-HkL.png
    - assets/page-1/images/blue-robot-mascot-logo-icon-design675467-55-1-traced-1-E6L.png
    - assets/page-1/images/image-9.png
    - assets/page-1/images/image-4.png
    - assets/page-1/images/image-13.png
    - assets/page-1/images/image-10-zZN.png
    - assets/page-1/images/gettyimages-463153413-612x612-1.png
    - assets/page-1/images/image-16.png
    - assets/page-1/images/frame-40-1bW.png
    - assets/page-1/images/image-7.png
    - assets/page-1/images/image-3.png
    - assets/page-1/images/image-6.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
